@host = http://localhost:8000

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "tranducvu234@gmail.com",
  "password": "P@ssw0rd!"
}

### Get reading data
GET http://192.168.0.100:8000/api/readings?deviceId=esp32-01&limit=100&sort=-1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MTMxNTgxOSwiZXhwIjoxNzYxMzE2NzE5fQ.86X3bB1gqWlU4yTdxbToSEp4s5FLh2W9lErOfERk9PE
X-Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MTMxNTgxOSwiZXhwIjoxNzYxOTIwNjE5fQ.c1tVjZInmL3jjSVThY7h8EdzYMkr6tYBO-dz1YFG_Qc
X-Client-Id: 68f20501066c05256f6b7298


