@host = https://kltn-api-dpqj.onrender.com

### Login
POST {{host}}/api/auth/login
Content-Type: application/json

{
  "email": "tranducvu234@gmail.com",
  "password": "P@ssw0rd!"
}

### Lấy thông tin điều khiển
GET {{host}}/api/device-control?device_id=esp32-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzOTM2NSwiZXhwIjoxNzY0NDQwMjY1fQ.QCYi7_rGj4PUluH8rBV9iV5zWxZwxp3CJjvV21XnpNg
X-Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzNzc0OSwiZXhwIjoxNzY1MDQyNTQ5fQ.kn8YQo-IZSw94PEHwVtldDXsbF3ZYcHUJLmASnlpQJU
X-Client-Id: 68f20501066c05256f6b7298


### Tắt máy bơm
PUT {{host}}/api/device-control
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQ0MjM1OCwiZXhwIjoxNzY0NDQzMjU4fQ.G8xxsIapCCwQeeRkVhhkRr2f544aao_5MKtTB7ceXII
X-Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzNzc0OSwiZXhwIjoxNzY1MDQyNTQ5fQ.kn8YQo-IZSw94PEHwVtldDXsbF3ZYcHUJLmASnlpQJU
X-Client-Id: 68f20501066c05256f6b7298

{
  "device_id": "esp32-01",
  "type": "light",
  "is_active": false
}

### Bật máy bơm tức thì và giữ 5s
PUT {{host}}/api/device-control
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzOTM2NSwiZXhwIjoxNzY0NDQwMjY1fQ.QCYi7_rGj4PUluH8rBV9iV5zWxZwxp3CJjvV21XnpNg
X-Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzNzc0OSwiZXhwIjoxNzY1MDQyNTQ5fQ.kn8YQo-IZSw94PEHwVtldDXsbF3ZYcHUJLmASnlpQJU
X-Client-Id: 68f20501066c05256f6b7298

{
  "device_id": "esp32-01",
  "type": "light",
  "is_active": true,
  "schedule_ms": 0,
  "duration_ms": 5000
}

### Hẹn giờ sau 10s, kéo dài 5s
PUT {{host}}/api/device-control
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzOTM2NSwiZXhwIjoxNzY0NDQwMjY1fQ.QCYi7_rGj4PUluH8rBV9iV5zWxZwxp3CJjvV21XnpNg
X-Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2NDQzNzc0OSwiZXhwIjoxNzY1MDQyNTQ5fQ.kn8YQo-IZSw94PEHwVtldDXsbF3ZYcHUJLmASnlpQJU
X-Client-Id: 68f20501066c05256f6b7298

{
  "device_id": "esp32-01",
  "type": "light",
  "is_active": true, 
  "schedule_ms":  1760723515672,
  "duration_ms": 5000
}

### Bật/tắt vô thời hạn 
PUT {{host}}/api/device-control
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MDcyMzkxMCwiZXhwIjoxNzYwNzI0ODEwfQ.LcTvuDlKjXnIgb27tMuZtQnnk2bRtfHqLit-jMYHstc
X-Refresh: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2OGYyMDUwMTA2NmMwNTI1NmY2YjcyOTgiLCJlbWFpbCI6InRyYW5kdWN2dTIzNEBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTc2MDcyMjg0OCwiZXhwIjoxNzYxMzI3NjQ4fQ.P8DVKgP5m94tbM_JS4Lv9HNjdRugRLGZocbDEsjR9ns
X-Client-Id: 68f20501066c05256f6b7298

{
  "device_id": "esp32-01",
  "is_active": false,
  "schedule_ms": 0,
  "duration_ms": 0
}
